version: '3.1'

services:
  app:
    build: ./app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - TOKEN=6321785491:AAFMBroA3AvF4rvDjus3mmMDXsiPCa43lXg
      - DB=postgresql
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_NAME=arma_bot_db
      - DB_USER=postgres
      - DB_PASS=vErY26hhh03PSWD
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=vErY26hhh03PSWD
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data: