"""init

Revision ID: 278cf20c61f8
Revises: b34ad97bbe36
Create Date: 2023-07-23 18:21:48.729081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '278cf20c61f8'
down_revision = 'b34ad97bbe36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
