"""init

Revision ID: 2c744389c5d0
Revises: ff7b882a363d
Create Date: 2023-07-24 20:02:47.493855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c744389c5d0'
down_revision = 'ff7b882a363d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'telegram_users', ['client'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'client')
    # ### end Alembic commands ###
