"""change roles

Revision ID: 3b7f47cb9ce8
Revises: 2b653104103e
Create Date: 2023-07-25 13:44:48.682406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b7f47cb9ce8'
down_revision = '2b653104103e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user_roles', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user_roles', sa.Column('client', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
