"""init

Revision ID: 4a66df1a086c
Revises: a8b50dbd912e
Create Date: 2023-07-24 18:23:55.480989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a66df1a086c'
down_revision = 'a8b50dbd912e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
