"""init

Revision ID: 4aa3412b34cc
Revises: 4a66df1a086c
Create Date: 2023-07-24 18:40:09.165158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa3412b34cc'
down_revision = '4a66df1a086c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('telegram_users_tg_id_key', 'telegram_users', type_='unique')
    op.drop_column('telegram_users', 'tg_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_users', sa.Column('tg_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('telegram_users_tg_id_key', 'telegram_users', ['tg_id'])
    # ### end Alembic commands ###
