"""init

Revision ID: 4f75a19b59fd
Revises: 278cf20c61f8
Create Date: 2023-07-24 14:51:38.075035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f75a19b59fd'
down_revision = '278cf20c61f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user_roles', sa.Column('verbose_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user_roles', 'verbose_name')
    # ### end Alembic commands ###
