"""init

Revision ID: 531ede77b122
Revises: 4f75a19b59fd
Create Date: 2023-07-24 14:55:59.163833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '531ede77b122'
down_revision = '4f75a19b59fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('verbose_name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('orders', sa.Column('status', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'status')
    op.drop_table('order_statuses')
    # ### end Alembic commands ###
