"""annotated test

Revision ID: 5cbf084c7a97
Revises: a506c15ce7d1
Create Date: 2023-07-25 12:40:45.477249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbf084c7a97'
down_revision = 'a506c15ce7d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
