"""init

Revision ID: a8b50dbd912e
Revises: aecdea96b61f
Create Date: 2023-07-24 16:00:45.788286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8b50dbd912e'
down_revision = 'aecdea96b61f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_in_orders', sa.Column('option_id', sa.Integer(), nullable=False))
    op.add_column('products_in_orders', sa.Column('option_value', sa.String(length=5256), nullable=False))
    op.drop_column('products_in_orders', 'option')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products_in_orders', sa.Column('option', sa.VARCHAR(length=5256), autoincrement=False, nullable=False))
    op.drop_column('products_in_orders', 'option_value')
    op.drop_column('products_in_orders', 'option_id')
    # ### end Alembic commands ###
