"""init

Revision ID: b34ad97bbe36
Revises: 
Create Date: 2023-07-23 18:15:40.440656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b34ad97bbe36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.Column('client', sa.Boolean(), nullable=False),
    sa.Column('hr', sa.Boolean(), nullable=False),
    sa.Column('sales_manager', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=256), nullable=True),
    sa.Column('last_name', sa.String(length=256), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['telegram_user_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=256), nullable=False),
    sa.Column('contacts', sa.String(length=512), nullable=False),
    sa.Column('summ', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('sales_manager', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sales_manager'], ['telegram_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_in_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('summ', sa.Integer(), nullable=False),
    sa.Column('summ_type', sa.String(length=64), nullable=False),
    sa.Column('option', sa.String(length=5256), nullable=False),
    sa.ForeignKeyConstraint(['order'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_in_orders')
    op.drop_table('orders')
    op.drop_table('telegram_users')
    op.drop_table('telegram_user_roles')
    # ### end Alembic commands ###
