"""init

Revision ID: b921acb1a745
Revises: 2c744389c5d0
Create Date: 2023-07-24 20:06:06.156113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b921acb1a745'
down_revision = '2c744389c5d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('telegram_user', sa.Integer(), nullable=True))
    op.drop_constraint('orders_client_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'telegram_users', ['telegram_user'], ['id'])
    op.drop_column('orders', 'client')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('client', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_client_fkey', 'orders', 'telegram_users', ['client'], ['id'])
    op.drop_column('orders', 'telegram_user')
    # ### end Alembic commands ###
