"""change roles

Revision ID: d180e2638057
Revises: 3b7f47cb9ce8
Create Date: 2023-07-25 15:06:20.632492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd180e2638057'
down_revision = '3b7f47cb9ce8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user_roles', sa.Column('permissions', sa.JSON(), nullable=False))
    op.drop_column('telegram_user_roles', 'hr')
    op.drop_column('telegram_user_roles', 'superuser')
    op.drop_column('telegram_user_roles', 'verbose_name')
    op.drop_column('telegram_user_roles', 'sales_manager')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user_roles', sa.Column('sales_manager', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('telegram_user_roles', sa.Column('verbose_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('telegram_user_roles', sa.Column('superuser', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('telegram_user_roles', sa.Column('hr', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('telegram_user_roles', 'permissions')
    # ### end Alembic commands ###
