"""init

Revision ID: d363cf307ae8
Revises: 4aa3412b34cc
Create Date: 2023-07-24 19:03:53.813234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd363cf307ae8'
down_revision = '4aa3412b34cc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
