#!/bin/bash
set -e


psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE DATABASE $ARMA_BOT___DB__NAME;
	CREATE USER $ARMA_BOT___DB__USER WITH PASSWORD '$ARMA_BOT___DB__PASS';
	GRANT ALL PRIVILEGES ON DATABASE $ARMA_BOT___DB__NAME TO $ARMA_BOT___DB__USER;
EOSQL