"""users

Revision ID: a506c15ce7d1
Revises: 0e423dfebed8
Create Date: 2023-07-25 12:09:49.066330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a506c15ce7d1'
down_revision = '0e423dfebed8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('verbose_name', sa.String(), nullable=False),
    sa.Column('superuser', sa.Boolean(), nullable=False),
    sa.Column('client', sa.Boolean(), nullable=False),
    sa.Column('hr', sa.Boolean(), nullable=False),
    sa.Column('sales_manager', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('telegram_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['telegram_user_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_users')
    op.drop_table('telegram_user_roles')
    # ### end Alembic commands ###
