"""change roles

Revision ID: cd479528856c
Revises: d180e2638057
Create Date: 2023-07-25 15:07:09.446800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd479528856c'
down_revision = 'd180e2638057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_user_roles', sa.Column('verbose_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_user_roles', 'verbose_name')
    # ### end Alembic commands ###
