"""annotated test

Revision ID: d57f781601d5
Revises: 5cbf084c7a97
Create Date: 2023-07-25 12:43:04.365619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57f781601d5'
down_revision = '5cbf084c7a97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
